### ISSUE TITLE
Add ignore property 

### ISSUE THREAD

**Issue by stalker3343** [bawa93/nuxtjs-vue-vuetify-vue-test-utils-jest-sample-project#1]
Hello. Thank you for the guide, it helped me a lot. During set up the testing, I found that nuxt is trying to build components and pages while preparing the store. You need add "ignore" property in finalConfig

 
    const finalConfig = Object.assign({}, nuxtConfig, resetConfig, {
      server: { port: constants.port },
      buildDir: constants.buildDir,
      ignore: ["**/components/**/*", "**/layouts/**/*", "**/pages/**/*"]
    })

**Comment by bawa93** [comment]
You are welcome 😊,  and thanks for pointing that out, i will fix it

**Comment by bawa93** [comment]
fixed
