### ISSUE TITLE
npm install failed with code 127

### ISSUE THREAD

**Issue by deni5n** [bawa93/nuxtjs-vue-vuetify-vue-test-utils-jest-sample-project#2]
Steps to reproduce

1. git clone git@github.com:bawa93/nuxtjs-vue-vuetify-vue-test-utils-jest-sample-project.git nuxtjs-test
2. npm install

What happens: during the step 2, process failed with error code 127. 

log:
```
npm ERR! code 127
npm ERR! path /home/user/nuxtjs-test/node_modules/fibers
npm ERR! command failed
npm ERR! command sh -c node build.js || nodejs build.js
npm ERR! sh: 1: node: not found
npm ERR! sh: 1: nodejs: not found
```
my node version 14.15.1

**Comment by bawa93** [comment]
hi, @deni5n it's tested on node version 12.x, I have to check on node 14.15
